name: Test scCellFie

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: "pip"
        cache-dependency-path: |
          requirements.txt

    - name: Install package
      run: |
        python -m pip install -e .

    - name: Test with pytest and coverage
      run: |
        pytest -vv --cov --cov-report xml

    - name: Check coverage with CodeCov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}